# Generated by Django 2.0.5 on 2018-05-24 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeuser',
            name='cedula',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de Cedula invalido , ej: V0123456', regex='^[V|E]{1}[0]{1}[0-9]{7,9}$')]),
        ),
        migrations.AlterField(
            model_name='completeuser',
            name='cod_area',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Codigo de Area invalido , ej: 0274', regex='^[0]{1}[2-4]{1}[1-9]{1}[1-9]{1}$')]),
        ),
        migrations.AlterField(
            model_name='completeuser',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='completeuser',
            name='num_telefono',
            field=models.CharField(max_length=7),
        ),
    ]
