# Generated by Django 2.0.5 on 2018-05-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeuser',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
