# Generated by Django 2.0.5 on 2018-05-25 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeuser',
            name='cedula',
            field=models.CharField(help_text='Fortamto: V012345678', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de Cedula invalido , ej: V0123456', regex='^[V|E]{1}[0]{1}[0-9]{7,9}$')]),
        ),
    ]
