# Generated by Django 2.0.5 on 2018-05-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180527_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeuser',
            name='estado',
            field=models.CharField(choices=[('Suspendido', 'Suspendido'), ('Bloqueado', 'Bloqueado'), ('Insolvente', 'Insolvente'), ('Solvente', 'Solvente')], default='Solvente', max_length=15),
        ),
    ]
