# Generated by Django 2.0.5 on 2018-06-16 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(blank=True, choices=[('A', 'Activo'), ('V', 'Vencido'), ('E', 'Eliminado')], default='A', max_length=1)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['id', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_caducidad', models.DateTimeField(default=datetime.datetime(2018, 6, 16, 23, 12, 28, 135749))),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('V', 'Vencido'), ('E', 'Eliminado')], default='A', max_length=1)),
                ('id_ejemplar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.Ejemplar')),
                ('id_ejemplar_revista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revista.EjemplarRevista')),
            ],
        ),
    ]
