# Generated by Django 2.0.5 on 2018-06-16 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0001_initial'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='id_ejemplar_revista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='revista.EjemplarRevista'),
        ),
    ]
