# Generated by Django 2.0.5 on 2018-06-03 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 6, 18, 27, 877637)),
        ),
    ]
