# Generated by Django 2.0.5 on 2018-05-23 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
