# Generated by Django 2.0.5 on 2018-06-16 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20180616_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 23, 18, 57, 182894)),
        ),
    ]
