# Generated by Django 2.0.5 on 2018-05-29 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20180528_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 9, 27, 58, 521969)),
        ),
    ]
