# Generated by Django 2.0.5 on 2018-06-03 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20180603_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 21, 28, 20, 382179)),
        ),
    ]
