# Generated by Django 2.0.5 on 2018-05-29 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_auto_20180528_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 9, 35, 6, 133106)),
        ),
    ]
