# Generated by Django 2.0.5 on 2018-06-16 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_auto_20180616_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 23, 34, 5, 810206)),
        ),
    ]
