# Generated by Django 2.0.5 on 2018-06-16 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_auto_20180616_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 14, 6, 24, 670069)),
        ),
    ]
