# Generated by Django 2.0.5 on 2018-06-10 00:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserva', '0008_auto_20180603_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(blank=True, choices=[('A', 'Activo'), ('V', 'Vencido'), ('E', 'Eliminado')], default='A', max_length=1)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['id', 'fecha'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('V', 'Vencido'), ('E', 'Eliminado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 10, 6, 33, 19, 693518)),
        ),
        migrations.AddField(
            model_name='historialreserva',
            name='id_reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva'),
        ),
        migrations.AddField(
            model_name='historialreserva',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
