# Generated by Django 2.0.5 on 2018-06-10 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_auto_20180609_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 0, 46, 36, 571369)),
        ),
    ]
