# Generated by Django 2.0.5 on 2018-06-12 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_auto_20180610_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_caducidad',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 1, 59, 45, 850919)),
        ),
    ]
