# Generated by Django 2.0.5 on 2018-05-27 18:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=80)),
                ('cuidad', models.CharField(max_length=80)),
                ('avenida', models.CharField(max_length=80)),
                ('calle', models.CharField(max_length=80)),
                ('edificio', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejemplar', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Formato de ejemplar incorrecto, ej: e1', regex='^[e]{1}[0-9]{1,3}$')])),
                ('estado', models.CharField(blank=True, choices=[('P', 'Prestado'), ('D', 'Disponible'), ('B', 'Bloqueado')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('cota', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('anio', models.PositiveSmallIntegerField()),
                ('lugar_publicacion', models.TextField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('descripcion', models.TextField(max_length=1000)),
                ('autor', models.ManyToManyField(to='libro.Autor')),
                ('biblioteca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Biblioteca')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='materia',
            field=models.ManyToManyField(to='libro.Materia'),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Libro'),
        ),
        migrations.AlterUniqueTogether(
            name='ejemplar',
            unique_together={('ejemplar', 'libro')},
        ),
    ]
