# Generated by Django 2.0.5 on 2018-06-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Prestado'), ('D', 'Disponible'), ('B', 'Bloqueado'), ('R', 'Reservado')], default='D', max_length=1),
        ),
    ]
