# Generated by Django 2.0.5 on 2018-05-24 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='biblioteca',
        ),
        migrations.AddField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libro.Biblioteca'),
        ),
    ]
