# Generated by Django 2.0.5 on 2018-05-25 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='ejemplar',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Formato de ejemplar incorrecto, ej: e1', regex='^[e]{1}[0-9]{1,3}$')]),
        ),
    ]
