# Generated by Django 2.0.5 on 2018-06-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20180616_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='vista',
        ),
    ]
