# Generated by Django 2.0.5 on 2018-06-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20180603_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='vista',
            field=models.ImageField(default='/images/1.jpg', null=True, upload_to='libro'),
        ),
    ]
