# Generated by Django 2.0.5 on 2018-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_remove_libro_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen_url',
            field=models.URLField(),
        ),
    ]
