# Generated by Django 2.0.5 on 2018-06-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='vista',
            field=models.ImageField(default='/images/default.png', null=True, upload_to='libro'),
        ),
    ]
