# Generated by Django 2.0.5 on 2018-05-29 01:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=datetime.datetime(2018, 5, 28, 21, 56, 51, 257673))),
                ('fecha_entrega', models.DateTimeField(default=datetime.datetime(2018, 5, 28, 21, 56, 51, 257728))),
                ('id_ejemplar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.Ejemplar')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
