# Generated by Django 2.0.5 on 2018-05-29 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 22, 4, 32, 269863)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 22, 4, 32, 269809)),
        ),
    ]
