# Generated by Django 2.0.5 on 2018-05-29 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0006_auto_20180528_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 0, 14, 6, 807112)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 0, 14, 6, 807060)),
        ),
    ]
