# Generated by Django 2.0.5 on 2018-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('autor_nombre', models.CharField(max_length=20)),
                ('autor_apellido', models.CharField(max_length=20)),
                ('tipo_material', models.CharField(max_length=20)),
            ],
        ),
    ]
