# Generated by Django 2.0.5 on 2018-05-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ejemplartesis',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ejemplartesis',
            name='tesis',
        ),
        migrations.AddField(
            model_name='tesis',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Prestado'), ('D', 'Disponible'), ('B', 'Bloqueado')], default='D', max_length=1),
        ),
        migrations.DeleteModel(
            name='EjemplarTesis',
        ),
    ]
