# Generated by Django 2.0.5 on 2018-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
