# Generated by Django 2.0.5 on 2018-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='estado',
            field=models.CharField(blank=True, choices=[('B', 'Bloqueado')], default='D', max_length=1),
        ),
    ]
