# Generated by Django 2.0.5 on 2018-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='materia',
        ),
        migrations.AddField(
            model_name='revista',
            name='area',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejemplarrevista',
            name='estado',
            field=models.CharField(blank=True, choices=[('P', 'Prestado'), ('D', 'Disponible'), ('B', 'Bloqueado'), ('R', 'Reservado')], default='D', max_length=1),
        ),
    ]
