# Generated by Django 2.0.5 on 2018-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='imagen',
            field=models.ImageField(default='/images/portada/default.png', upload_to='images/portada'),
        ),
        migrations.AddField(
            model_name='revista',
            name='imagen_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
